server:
  port: 9086

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

services:
  holder: https://jsonplaceholder.typicode.com/
  photos: photos
  users: users
  albums: albums
